### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/js-encryptedfs#20]
Documentation needs to be created and should include:
- Overview (explanation of upper and lower directory/chunks etc)
- Installation
- Usage
- Warnings (e.g. for usage of context control actions like chdir and setuid etc.)

This can go into `README.md`

**Comment by robert-cronin** [comment]
Function docs also need to be implemented. A draft of both function documentation and the `README.md` are a part of PR #19

**Comment by CMCDragonkai** [comment]
API docs should be autogenerated. We used jsdocs or something back in js-virtualfs. But we can do something different with something designed for typescript.

**Comment by CMCDragonkai** [comment]
As for usage. Keep it light, README.md should be fine. Since we are just saying it works like node fs, but encrypted.

**Comment by robert-cronin** [comment]
Yes there is [typedoc](http://typedoc.org/) I have added this as a separate commit because I think its noteworthy. Documentation looks quite good and we can host it on github pages. Once you merge #19 I will publish it to github pages :+1:
