### ISSUE TITLE
Generated docs should be viewable directly from Github

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/js-encryptedfs#27]
There are 2 ways to do this.

Do it same as js-virtualfs, we provide a link for raw rendering of a github repo. See js-virtualfs README.md for example since the docs is index.html.

Or use gh-pages to provide a "pages" version of this repo.

Github has since improved their pages feature. So I think we can do the latter: https://help.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site (it appears it can do it directly from the docs directory).

Much better than any man pages!

**Comment by robert-cronin** [comment]
docs are now directly viewable from https://matrixai.github.io/js-encryptedfs/
