### ISSUE TITLE
NPM releases should create tags in the repo

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/js-encryptedfs#28]
Furthermore we can integrate the pushing to the CI/CD pipeline.

However I'm not sure yet, since it's not every commit results in a release. It should activate only when we decide there should be a release.

We can leave it for manual execution for now.

Either way, I'm not sure if you have pushed up an npm release, because I don't see any git tags. Note that you must do `git push --tags` to do it.

Should investigate how to do this automatically with the pipeline, Gitlab CI does have manual pipelines as well I remember.

**Comment by robert-cronin** [comment]
This was done manually for the previous release, this issue remains for the CI/CD integration for automatic tag pushing

**Comment by CMCDragonkai** [comment]
You just need to do `git push --tags`.

On 11 June 2020 13:58:18 GMT+10:00, Robbie Cronin <notifications@github.com> wrote:
>This was done manually for the previous release, this issue remains for
>the CI/CD integration for automatic tag pushing
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MatrixAI/js-encryptedfs/issues/28#issuecomment-642391208

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by robert-cronin** [comment]
yeah, that's the command I've used, it seems to be showing up okay: https://github.com/MatrixAI/js-encryptedfs/releases/tag/v0.1.0
We can put `git push --tags` in the `gitlab-ci.yml` file I guess?

**Comment by CMCDragonkai** [comment]
How would that work if the repo hasn't received your tags from your local repo?

On 11 June 2020 14:36:42 GMT+10:00, Robbie Cronin <notifications@github.com> wrote:
>yeah, that's the command I've used, it seems to be showing up okay:
>https://github.com/MatrixAI/js-encryptedfs/releases/tag/v0.1.0
>We can put `git push --tags` in the `gitlab-ci.yml` file I guess?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MatrixAI/js-encryptedfs/issues/28#issuecomment-642400931

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by robert-cronin** [comment]
Closing on account of migration to gitlab
