### ISSUE TITLE
Unit testing the EFS API

### ISSUE THREAD

**Issue by ll-aashwin-ll** [MatrixAI/js-encryptedfs#3]
Each method exposed by EncryptedFS should be unit tested to ensure the expected behaviour of the method is met. This allows all changes made to the code base to be tested against the test suite to ensure there are no breaking changes in the updates.

As of now, the units test are constructed using ava tests.

**Comment by CMCDragonkai** [comment]
This is done for now, we'll assume we do unit tests for each new feature from now on.
